"use client"

import React from "react"
import { Heading, Text } from "@medusajs/ui"

export default function TermsPage() {
  return (
    <div className="bg-black min-h-screen py-16">
      <div className="container mx-auto px-4 md:px-6 lg:px-8 max-w-4xl">
        <Heading
          level="h1"
          className="text-4xl md:text-5xl font-bold text-white text-center mb-12"
        >
          Terms and Conditions
        </Heading>

        <div className="prose prose-invert prose-lg max-w-none">
          <div className="bg-gray-800/50 backdrop-blur-sm rounded-lg p-8 border border-gray-700/50">
            <h2 className="text-2xl font-bold text-light-green mt-8 mb-4">
              PLEASE READ THESE TERMS CAREFULLY BEFORE USING OUR WEB SITE. USE
              OF THIS WEB SITE INDICATES YOUR ACCEPTANCE OF THESE TERMS.
            </h2>

            <p className="mb-6">
              EVERY CARE HAS BEEN TAKEN TO ENSURE THAT DESCRIPTIONS, AND PRICES
              ARE CORRECT. WE RESERVE THE RIGHT TO AMEND PRICES IN THE EVENT OF
              A CHANGE IN VAT, IN DUTY OR INTERNATIONAL PRICING. PLEASE NOTE
              THAT THERE MAY BE SOME VARIATION IN THE COLOUR OF GOODS SHOWN ON
              THE WEB SITE DUE TO THE LIMITATIONS OF PHOTOGRAPHIC AND WEB
              PROCESSES AND WE CANNOT BE HELD RESPONSIBLE FOR ANY VARIATIONS IN
              COLOUR THAT MAY ARISE CAUSED BY YOUR BROWSER OR COMPUTER SOFTWARE.
            </p>

            <p className="mb-6">
              THIS CURRENT WEB SITE THAT YOU ARE ON MAINTAINS THIS SITE AND ALL
              THE INFORMATION, COMMUNICATIONS, SOFTWARE, SCRIPTING, PHOTOS,
              TEXT, GRAPHICS, IMAGES AND OTHER MATERIALS AND SERVICES FOUND ON
              THE SITE (COLLECTIVELY "CONTENT"), FOR THE USE OF ITS CUSTOMERS,
              EMPLOYEES, AND MEMBERS OF THE GENERAL PUBLIC.
            </p>

            <h2 className="text-2xl font-bold text-light-green mt-8 mb-4">
              ACCEPTANCE OF CONTRACT TERMS
            </h2>
            <p className="mb-6">
              IN EXCHANGE FOR USING THIS CURRENT WEB SITE THAT YOU ARE ON, YOU
              AGREE TO BE BOUND EXCLUSIVELY BY THESE TERMS AND TO COMPLY WITH
              ALL APPLICABLE LAWS AND REGULATIONS. YOU REPRESENT YOU HAVE THE
              LEGAL AUTHORITY TO ACCEPT THESE TERMS OF USE ON BEHALF OF YOURSELF
              OR ANY PARTY YOU REPRESENT. IF ANY PROVISION OF THESE TERMS OF USE
              IS HELD TO BE INVALID BY ANY LAW, RULE, ORDER, OR REGULATION OF
              ANY GOVERNMENT OR BY THE FINAL DETERMINATION OF ANY STATE OR
              FEDERAL COURT, SUCH INVALIDITY SHALL NOT AFFECT THE ENFORCEABILITY
              OF ANY OTHER PROVISION OF THE TERMS OF USE.
            </p>

            <p className="mb-6">
              IF YOU DO NOT AGREE TO THESE TERMS, PLEASE DO NOT USE OUR SITE.
              THIS CURRENT WEB SITE THAT YOU ARE ON IS CONTROLLED AND OPERATED
              IN WHOLE OR IN PART BY THE WEB SITE OWNER FROM ITS OFFICES WITHIN
              THE UNITED STATES. BY ACCESSING THE WEB SITE, YOU AGREE THAT THE
              STATUTES AND LAWS OF THE UNITED STATES AND THE STATE OF
              CALIFORNIA, WITHOUT REGARD TO CONFLICTS OF LAWS, WILL APPLY TO ALL
              MATTERS RELATING TO USE OF THE WEB SITE, AND YOU AGREE THAT ANY
              LITIGATION RELATING IN ANY WAY TO THE USE OF THE WEB SITE SHALL BE
              SUBJECT TO THE JURISDICTION OF THE STATE OR FEDERAL COURTS IN THE
              U.S.A.
            </p>

            <p className="mb-6">
              THOSE WHO ACCESS THIS CURRENT WEB SITE FROM OTHER LOCATIONS DO SO
              AT THEIR OWN RISK AND ARE RESPONSIBLE FOR COMPLIANCE WITH
              APPLICABLE LOCAL LAWS. THE WEB SITE OWNER MAKES NO REPRESENTATION
              THAT THE CONTENT IN THE SITE IS APPROPRIATE OR AVAILABLE FOR USE
              IN OTHER LOCATIONS OR THAT ACCESS TO IT FROM OUTSIDE THE U.S.A. IS
              LEGAL. AS A CONDITION OF YOUR USE OF THE SITE, YOU WARRANT TO THIS
              CURRENT WEB SITE THAT YOU WILL NOT USE THE SITE FOR ANY PURPOSE
              THAT IS UNLAWFUL OR PROHIBITED BY THE TERMS, CONDITIONS, AND
              NOTICES CONTAINED HEREIN. YOU SHALL NOT, AT ANY TIME, (A) REVERSE
              ENGINEER, DECOMPILE OR DISASSEMBLE ANY PORTION OF THE SITE OR
              TAMPER IN ANY WAY WITH THE OPERATION OF THE SITE, OR (B) INSERT OR
              MAKE USE OF ANY TYPE OF DISABLING DEVICE INCLUDING, BUT NOT
              LIMITED TO, VIRUSES, WORMS, TROJAN HORSES, TIME BOMBS, OR ANY
              SIMILAR DEVICE THAT MAY IMPAIR, DAMAGE, OR INTERFERE WITH THE
              PROPER WORKING ORDER OF THE SITE. YOU ACKNOWLEDGE THAT THE WEB
              SITE OWNER RESERVES THE RIGHT IN ITS SOLE DISCRETION TO REFUSE OR
              TERMINATE ACCESS TO THE SITE BY YOU AT ANY TIME.
            </p>

            <h2 className="text-2xl font-bold text-light-green mt-8 mb-4">
              RESTRICTIONS ON USE OF CONTENT
            </h2>
            <p className="mb-6">
              YOU ACKNOWLEDGE THAT THE CONTENT IS THE PROPERTY OF THE WEB SITE
              OWNER AND IS PROTECTED IN THE U.S. AND INTERNATIONALLY BY A
              VARIETY OF LAWS, INCLUDING BUT NOT LIMITED TO, COPYRIGHT LAWS AND
              TREATY PROVISIONS, TRADEMARK LAWS AND OTHER PROPRIETARY RIGHTS
              LAWS. IN ADDITION TO THE WEB SITE OWNER OWNERSHIP OF THE CONTENT,
              THE WEB SITE OWNER OR ITS LICENSORS OWNS A COPYRIGHT IN THE
              SELECTION, COORDINATION AND ARRANGEMENT OF THE CONTENT. NOTHING
              CONTAINED IN THIS SITE SHALL BE CONSTRUED AS CONFERRING ANY
              LICENSE OR RIGHT TO ANY COPYRIGHT, TRADEMARK OR OTHER PROPRIETARY
              INTEREST OF THIS CURRENT WEB SITE OR ANY THIRD PARTY. THE SITE AND
              THE CONTENT MAY NOT BE COPIED, DISTRIBUTED, OR REPRODUCED IN ANY
              WAY, WITHOUT THE PRIOR WRITTEN CONSENT OF THIS CURRENT WEB SITE
              OWNER, EXCEPT THAT YOU MAY PRINT A COPIES OF THE CONTENT FOR
              PERSONAL, INFORMATIONAL, NON-COMMERCIAL USE PROVIDED THAT (I) ALL
              COPYRIGHT, TRADEMARK AND OTHER PROPRIETARY NOTICES ARE KEPT
              INTACT, AND (II) THE CONTENT IS NOT MODIFIED IN ANY WAY. THE
              PERMISSION TERMINATES AUTOMATICALLY IF YOU BREACH ANY OF THE TERMS
              OF USE. THE WEB SITE OWNER IS NOT GRANTING YOU ANY PERMISSION TO
              USE THE CONTENT OTHER THAN THE PERMISSION EXPRESSLY STATED IN
              THESE TERMS OF USE.
            </p>

            <h2 className="text-2xl font-bold text-light-green mt-8 mb-4">
              REVISIONS
            </h2>
            <p className="mb-6">
              THE WEB SITE OWNER MAY REVISE OR WITHDRAW THE CONTENT, IN WHOLE OR
              IN PART, AT ANY TIME WITHOUT NOTICE. THE WEB SITE OWNER MAY AT ANY
              TIME REVISE THESE TERMS OF USE BY UPDATING THIS POSTING. BY USING
              THE SITE, YOU AGREE TO BE BOUND BY ANY SUCH REVISIONS AND YOU
              AGREE TO PERIODICALLY VISIT THIS PAGE TO DETERMINE THE THEN
              CURRENT TERMS OF USE TO WHICH YOU ARE BOUND.
            </p>

            <h2 className="text-2xl font-bold text-light-green mt-8 mb-4">
              LINKS TO THIRD PARTY WEB SITES
            </h2>
            <p className="mb-6">
              THE SITE MAY CONTAIN HYPERLINKS TO WEB SITES OPERATED BY PARTIES
              OTHER THAN THE WEB SITE OWNER. SUCH HYPERLINKS ARE PROVIDED FOR
              YOUR REFERENCE ONLY. THE WEB SITE OWNER DOES NOT CONTROL SUCH WEB
              SITES AND IS NOT RESPONSIBLE FOR THEIR CONTENTS. THE WEB SITE
              OWNER'S INCLUSION OF HYPERLINKS TO SUCH WEB SITES DOES NOT IMPLY
              ANY ENDORSEMENT OF THE MATERIAL ON SUCH WEB SITES OR ANY
              ASSOCIATION WITH THEIR OPERATORS. THE WEB SITE OWNER IS NOT
              RESPONSIBLE FOR DAMAGES OR LOSSES CAUSED BY ANY DELAYS, DEFECTS OR
              OMISSIONS THAT MAY EXIST IN THE SERVICES, INFORMATION OR OTHER
              CONTENT PROVIDED IN SUCH WEB SITES, WHETHER ACTUAL, ALLEGED,
              CONSEQUENTIAL OR PUNITIVE. THE WEB SITE OWNER MAKES NO GUARANTEES
              OR REPRESENTATIONS AS TO, AND SHALL HAVE NO LIABILITY FOR, ANY
              ELECTRONIC CONTENT DELIVERED BY ANY THIRD PARTY, INCLUDING,
              WITHOUT LIMITATION, THE ACCURACY, SUBJECT MATTER, QUALITY OR
              TIMELINESS OF ANY ELECTRONIC CONTENT.
            </p>

            <h2 className="text-2xl font-bold text-light-green mt-8 mb-4">
              DISCLAIMER OF WARRANTY; LIMITATION OF LIABILITY; INDEMNITY
            </h2>
            <p className="mb-6">
              IN NO EVENT WILL THE WEB SITE OWNER, ITS SUPPLIERS, OR OTHER THIRD
              PARTIES MENTIONED AT THIS SITE BE LIABLE FOR ANY DAMAGES
              WHATSOEVER (INCLUDING, WITHOUT LIMITATION, THOSE RESULTING FROM
              LOST PROFITS, LOST DATA OR BUSINESS INTERRUPTION) ARISING OUT OF
              THE USE, INABILITY TO USE, OR THE RESULTS OF USE OF THIS SITE, ANY
              WEB SITES LINKED TO THIS SITE, OR THE MATERIALS OR INFORMATION OR
              SERVICES CONTAINED AT ANY OR ALL SUCH SITES, WHETHER BASED ON
              WARRANTY, CONTRACT, TORT OR ANY OTHER LEGAL THEORY AND WHETHER OR
              NOT ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. IF YOUR USE OF THE
              MATERIALS, INFORMATION OR SERVICES FROM THIS SITE RESULTS IN THE
              NEED FOR SERVICING, REPAIR OR CORRECTION OF EQUIPMENT OR DATA, YOU
              ASSUME ALL COSTS THEREOF. APPLICABLE LAW MAY NOT ALLOW THE
              EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO
              THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU.
            </p>

            <h2 className="text-2xl font-bold text-light-green mt-8 mb-4">
              TRADEMARKS AND SERVICE MARKS
            </h2>
            <p className="mb-6">
              THE TRADEMARKS, LOGOS AND SERVICE MARKS ("MARKS") DISPLAYED ON
              THIS SITE ARE REGISTERED, COMMON LAW TRADEMARKS AND ARE THE
              PROPERTY OF THE WEB SITE OWNER OR OTHER THIRD PARTIES. YOU ARE NOT
              PERMITTED TO USE THE MARKS WITHOUT THE PRIOR WRITTEN CONSENT OF
              THE WEB SITE OWNER OR SUCH THIRD PARTY WHICH MAY OWN THE MARKS.
              NOTHING ON THIS SITE SHOULD BE INTERPRETED, BY IMPLICATION OR
              OTHERWISE, AS GRANTING PERMISSION OR LICENSE TO USE THE MARKS,
              WHETHER THE WEB SITE OWNER MARKS OR THOSE OF A THIRD PARTY.
            </p>
          </div>
        </div>

        <div className="mt-12 text-center">
          <Text className="text-gray-300">Last updated: April 16, 2025</Text>
        </div>
      </div>
    </div>
  )
}
